# This workflow will make hopeit.aws package and deploy on PyPI

name: hopeit.aws PyPI Publishing

on:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: make ci-deps
        run: PYTHONVERSION=${{ matrix.python-version }} make ci-deps

      - name: lint
        run: |
          make lint

      - name: test
        run: |
          make test

      - name: make dist-plugin aws-s3
        run: |
          make PLUGINFOLDER=plugins/aws/s3/ dist-plugin

      - name: publish plugin aws-s3 on PyPI
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          make PLUGINFOLDER=plugins/aws/s3/ publish-plugin-pypi
