# This workflow will make hopeit.aws package and deploy on PyPI

name: hopeit.aws Test PyPI Publishing

on:
  release:
    types: [unpublished, prereleased]

jobs:
  upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Build and publish Python 🐍 distributions 📦 to PyPI
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        make dev-deps
    - name: QA
      run: |
        make qa        
    - name: make plugin aws/s3
      run: |
        make PLUGINFOLDER=plugins/aws/s3/ dist-plugin
    - name: Publish plugin aws/s3 on Test PyPI
      env: 
        TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN_ALL }}
      run: |
        make PLUGINFOLDER=plugins/aws/s3 pypi-test-plugin
