# This workflow will make hopeit.aws package and deploy on PyPI

name: hopeit.aws Test PyPI Publishing

on:
  release:
    types: [unpublished, prereleased]

jobs:
  upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    
    - name: install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    
    - name: make ci-deps
      run: PYTHONVERSION=${{ matrix.python-version }} make ci-deps

    - name: make dist-plugin aws_s3
      run: |
        make PLUGINFOLDER=plugins/aws/s3/ dist-plugin
    
    - name: publish aws_s3 on Test PyPI
      env: 
        TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN_ALL }}
      run: |
        make PLUGINFOLDER=plugins/aws/s3/ publish-plugin-pypi-test
